; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.15 on Tue Mar 14 2023 14:12:21 GMT+0000 (GMT)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation